services:
  - type: web
    name: speed-test-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: your_mongodb_connection_string_here
    plan: free
    region: oregon
    autoDeploy: true
